language: objective-c
osx_image: xcode8.1
script:
  - xcodebuild -workspace Sjtek.xcworkspace -scheme Sjtek -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xcodebuild test -workspace Sjtek.xcworkspace -scheme Sjtek -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1'